// Code generated by "stringer -type=ScoringMode -output=scoringmode_string.g.go"; DO NOT EDIT.

package games

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Negative-0]
	_ = x[Standard-1]
}

const _ScoringMode_name = "NegativeStandard"

var _ScoringMode_index = [...]uint8{0, 8, 16}

func (i ScoringMode) String() string {
	if i < 0 || i >= ScoringMode(len(_ScoringMode_index)-1) {
		return "ScoringMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScoringMode_name[_ScoringMode_index[i]:_ScoringMode_index[i+1]]
}
