name: Deploy to Dev Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh scripts/build.sh
        env:
          CI: true
      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Publish Artifact
        run: sh scripts/publish.sh
      - name: Deploy API
        run: sh scripts/deploy.sh
        env:
          AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
          CODE_BUCKET_NAME: oh-hell-backend-artifacts
          SSL_CERT_ARN: ${{ secrets.SSL_CERT_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
